#ifndef CPPARSEC_SHORTMACRO_H

#include "cpparsec_core.h"

#define CP_MAKE CPPARSEC_MAKE
#define CP_SAVE CPPARSEC_SAVE
#define CP_SKIP CPPARSEC_SKIP
#define CP_FAIL_IF CPPARSEC_FAIL_IF
#define CP_FAIL CPPARSEC_FAIL
#define CP_MAKE CPPARSEC_MAKE
#define CP_MAKE_METHOD CPPARSEC_MAKE_METHOD

#endif /* CPPARSEC_SHORTMACRO_H */
